AWSTemplateFormatVersion: "2010-09-09"
Description: Cloud Formation Template
Parameters:
  SagemakerEndpoints:
    Type: String
Resources:
  SESReceiptRuleSet:
    Type: 'AWS::SES::ReceiptRuleSet'
    Properties:
      RuleSetName: "cf-coms6998hw3"
  SESReceiptRule:
    Type: "AWS::SES::ReceiptRule"
    Properties:
      RuleSetName: !Ref SESReceiptRuleSet
      Rule:
        Enabled: true
        ScanEnabled: true
        Recipients:
          - "yutongc123@yutongc123.com"
        Actions:
          -
            S3Action:
              BucketName: !Ref bucket1
        Enabled: true
        Name: "cf_ses_to_s3"
        TlsPolicy: "Optional"
  cflambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: hw3-lambda-cloud-formation
        S3Key: lambda.zip
      Description: "lambda"
      MemorySize: 128
      Layers:
        - arn:aws:lambda:us-east-1:176363299110:layer:numpy:1
      Environment:
        Variables:
          ENDPOINT_NAME: !Ref SagemakerEndpoints
      Handler: lambda_function.lambda_handler
      Role: "arn:aws:iam::176363299110:role/service-role/spam-detect-role-higia4f8"
      Timeout: 30
      Runtime: python3.6
      FunctionName: spam-detect-cloudformation
  bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: email-received-cloud-formation
  bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: train-cloud-formation
  cfBucketPolicy1:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: email-received-cloud-formation
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSESPuts
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: s3:PutObject
            Resource: "arn:aws:s3:::email-received-cloud-formation/*"
            Condition:
              StringEquals:
                aws:Referer: "176363299110"
